# Generated by Django 3.2.5 on 2021-07-15 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_period_avoid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anchoredcourse",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="courses.course"
            ),
        ),
    ]
