# Generated by Django 3.2.5 on 2021-07-17 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_alter_anchoredcourse_course"),
    ]

    operations = [
        migrations.CreateModel(
            name="SolvedSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("solved", models.BooleanField(default=False)),
                ("finished", models.BooleanField(default=False)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.organization",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ScheduleItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_pk", models.PositiveIntegerField()),
                ("period_number", models.PositiveIntegerField()),
                ("period_start", models.TimeField()),
                ("period_end", models.TimeField()),
                ("room_pk", models.PositiveIntegerField()),
                ("room_name", models.CharField(max_length=200)),
                ("teacher_name", models.CharField(max_length=200)),
                ("course_name", models.CharField(max_length=150)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.organization",
                    ),
                ),
                (
                    "solved_schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.solvedschedule",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
